services:
  frontend:
    container_name: "frontend"
    build:
      context: ./frontend
    ports:
      - 5173:5173
    network_mode: "host"

  backend:
    container_name: "backend"
    build:
      context: ./backend
    ports:
      - 8000:8000
